FROM nginx:latest
EXPOSE 80
COPY default.conf /etc/nginx/conf.d/default.conf

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait